<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"
                xmlns="http://www.w3.org/1999/xhtml">
    
    <xsl:output method="xml"
                doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN"
                doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"
                encoding="UTF-8"
                indent="yes"
    />
	
    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <meta charset="UTF-8"/>
                <link rel="stylesheet" type="text/css" href="style.css" />
                <title>List of Payments</title>
            </head>
            <body>
                <xsl:apply-templates select="payments"/>
            </body>
        </html>
    </xsl:template>	
	
	<xsl:template match="payments">
		<h1>List of Payments</h1>               
                <h4>Automatically generated by application Expense-Manager</h4>
                    <div class="pageColumnLeft">
                        <h3>Survey</h3>
                            <h4>Number of payments:<xsl:text> </xsl:text><xsl:value-of select="count"/></h4>                                
                            <h4>Amount of payments:<xsl:text> </xsl:text><xsl:value-of select="sum"/></h4>                                   
                            <h4>The number of incoming payments:<xsl:text> </xsl:text><xsl:value-of select="incomingCount"/></h4>                                
                            <h4>Number of outgoing payments:<xsl:text> </xsl:text><xsl:value-of select="outgoingCount"/></h4>                              
                            <h4>Amount of incoming payments:<xsl:text> </xsl:text><xsl:value-of select="incomingSum"/></h4>                                
                            <h4>Amount of outcoming payments:<xsl:text> </xsl:text><xsl:value-of select="outgoingSum"/></h4>
                            <h4>Highest incoming payment:<xsl:text> </xsl:text><xsl:value-of select="highestIncoming"/></h4>
                            <h4>Highest outcoming payment:<xsl:text> </xsl:text><xsl:value-of select="highestOutgoing"/></h4>
                    </div>
                    <table>                    
			<tr>
                            <th><b>Date</b></th>
							<th><b>Description</b></th>
                            <th><b>Account</b></th>
                            <th><b>Subject</b></th>
                            <th><b>Category</b></th>
                            <th><b>Amount</b></th>
			</tr>
                        
			<xsl:for-each select="payment">
				<tr>
                                    <td><xsl:value-of select="date"/></td>
                                    <td><xsl:value-of select="description"/></td>
                                    <td><xsl:value-of select="account-name"/></td>
                                    <td><xsl:value-of select="subject-name"/></td>
                                    <td><xsl:value-of select="category-name"/></td>
                                    <td><xsl:value-of select="amount"/></td>
				</tr>
			</xsl:for-each>
		</table>                
	</xsl:template>      
        	 
</xsl:stylesheet>