/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Vector;
import project.Account;
import project.AccountManagerImpl;
import project.Category;
import project.CategoryManagerImpl;
import project.Currency;
import project.CurrencyManagerImpl;
import project.ExpenseManagerImpl;
import project.Payment;
import project.PaymentManagerImpl;
import project.Subject;
import project.SubjectManagerImpl;

/**
 *
 * @author rk
 */
public class MainFrame extends javax.swing.JFrame {

    
   // private final ResourceBundle localization = ResourceBundle.getBundle("localization",new Locale("SK")); 
    private final ResourceBundle localization = ResourceBundle.getBundle("localization",Locale.US); 
    private static AccountManagerImpl accountManager = new AccountManagerImpl();
    private static PaymentManagerImpl paymentManager = new PaymentManagerImpl();
    private static ExpenseManagerImpl expenseManager = new ExpenseManagerImpl();
    private static CurrencyManagerImpl currencyManager = new CurrencyManagerImpl();
    private static SubjectManagerImpl subjectManager = new SubjectManagerImpl();
    private static CategoryManagerImpl categoryManager = new CategoryManagerImpl(); 
    private List<Payment> toTable = new ArrayList<>();
    
    
    

    
    
    //private JPaymentTableModel paymentTableModel;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        accountList = new javax.swing.JComboBox();
        subjectList = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        paymentTableModel = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();

        jFrame1.setTitle(localization.getString("addPayment"));
        jFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFrame1.setMaximumSize(new java.awt.Dimension(550, 300));
        jFrame1.setMinimumSize(new java.awt.Dimension(550, 300));
        jFrame1.setPreferredSize(new java.awt.Dimension(550, 300));
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new Vector<Account>(accountManager.findAllAccounts())));
        jFrame1.getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 320, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new Vector<Subject>(subjectManager.findAllSubjects())));
        jFrame1.getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 320, 30));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new Vector<Category>(categoryManager.findAllCategory())));
        jFrame1.getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 320, 30));
        jFrame1.getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 170, 30));

        jButton6.setText(localization.getString("addPayment"));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 200, 30));

        jLabel4.setText(localization.getString("account"));
        jFrame1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel5.setText(localization.getString("subject"));
        jFrame1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel6.setText(localization.getString("category"));
        jFrame1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel7.setText(localization.getString("date"));
        jFrame1.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jLabel8.setText(localization.getString("amount"));
        jFrame1.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jTextField1.setText("0.00");
        jFrame1.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 90, 30));

        jLabel9.setText(localization.getString("description"));
        jFrame1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 320, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ExpenseUlimate Manager");
        setMaximumSize(new java.awt.Dimension(780, 530));
        setMinimumSize(new java.awt.Dimension(780, 530));
        setPreferredSize(new java.awt.Dimension(780, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Vector vec = new Vector<Account>(accountManager.findAllAccounts());
        Account tempAcc = new Account();
        tempAcc.setId(0L);
        tempAcc.setName("-- " + localization.getString("allAccounts") + " --");
        vec.add(0, tempAcc);
        accountList.setModel(new javax.swing.DefaultComboBoxModel(vec));
        accountList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                accountListItemStateChanged(evt);
            }
        });
        getContentPane().add(accountList, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 11, 300, 30));

        Vector vec2 = new Vector<Subject>(subjectManager.findAllSubjects());
        Subject tempSub = new Subject();
        tempSub.setId(0L);
        tempSub.setName("-- " + localization.getString("allSubjects") + " --");
        vec2.add(0, tempSub);
        subjectList.setModel(new javax.swing.DefaultComboBoxModel(vec2));
        getContentPane().add(subjectList, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 49, 300, 30));

        jLabel1.setText("Account:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setText("Subject:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(2);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 404, 750, 50));

        paymentTableModel.setModel(new JPaymentTableModel(localization));
        paymentTableModel.setMaximumSize(null);
        paymentTableModel.getColumnModel().getColumn(0).setPreferredWidth(300);
        paymentTableModel.getColumnModel().getColumn(1).setPreferredWidth(100);
        paymentTableModel.getColumnModel().getColumn(2).setPreferredWidth(150);
        paymentTableModel.getColumnModel().getColumn(3).setPreferredWidth(150);
        paymentTableModel.getColumnModel().getColumn(4).setPreferredWidth(100);
        jScrollPane2.setViewportView(paymentTableModel);
        //PaymentManagerImpl manager = new PaymentManagerImpl();
        //  List<Payment> list = manager.findAllPayments();
        //  ((JPaymentTableModel)paymentTableModel.getModel()).refresh(list);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 750, 250));

        jLabel3.setText("Payments:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jButton1.setText("Add Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 150, -1));

        jButton2.setText("Delete Payment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 150, -1));

        jButton3.setText("EditPayment");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 150, -1));

        jButton4.setText("Generate HTML report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 200, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 142, 30));
        getContentPane().add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 142, 30));

        jButton5.setText("Show");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 128, 70));

        jCheckBox1.setText("Use Date");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jMenu2.setText("File");

        jMenuItem1.setText("Exit");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Account");

        jMenuItem2.setText("Add");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Delete");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Edit");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Subject");

        jMenuItem5.setText("Add");
        jMenu6.add(jMenuItem5);

        jMenuItem6.setText("Delete");
        jMenu6.add(jMenuItem6);

        jMenuItem7.setText("Edit");
        jMenu6.add(jMenuItem7);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Currency");

        jMenuItem8.setText("Add");
        jMenu7.add(jMenuItem8);

        jMenuItem9.setText("Delete");
        jMenu7.add(jMenuItem9);

        jMenuItem10.setText("Edit");
        jMenu7.add(jMenuItem10);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Category");

        jMenuItem11.setText("Add");
        jMenu8.add(jMenuItem11);

        jMenuItem12.setText("Delete");
        jMenu8.add(jMenuItem12);

        jMenuItem13.setText("Edit");
        jMenu8.add(jMenuItem13);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("XML");

        jMenuItem14.setText("Generate");
        jMenu9.add(jMenuItem14);

        jMenuBar1.add(jMenu9);

        jMenu1.setText("Help");

        jMenuItem15.setText("Help");
        jMenu1.add(jMenuItem15);

        jMenuItem16.setText("About");
        jMenu1.add(jMenuItem16);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_accountListItemStateChanged
            // TODO add your handling code here:
    }//GEN-LAST:event_accountListItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           jFrame1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        update();
    }//GEN-LAST:event_jButton5MouseClicked

    public void update(){
        if((((Account)accountList.getSelectedItem()).getId() == 0) && (((Subject)subjectList.getSelectedItem()).getId() == 0) && (jCheckBox1.isSelected()))
            toTable = paymentManager.findAllPayments(jDateChooser2.getDate(),jDateChooser3.getDate());
        
        if((((Account)accountList.getSelectedItem()).getId() == 0) && (((Subject)subjectList.getSelectedItem()).getId() != 0) && (jCheckBox1.isSelected()))
            toTable = expenseManager.getAllPaymentsBySubject(((Subject)subjectList.getSelectedItem()).getId(), jDateChooser2.getDate(),jDateChooser3.getDate());
            
        if((((Account)accountList.getSelectedItem()).getId() != 0) && (((Subject)subjectList.getSelectedItem()).getId() == 0) && (jCheckBox1.isSelected()))
            toTable = expenseManager.getAllPaymentsByAccount(((Account)accountList.getSelectedItem()).getId(), jDateChooser2.getDate(),jDateChooser3.getDate());
        
        if((((Account)accountList.getSelectedItem()).getId() != 0) && (((Subject)subjectList.getSelectedItem()).getId() != 0) && (jCheckBox1.isSelected()))
            toTable = expenseManager.getAllPaymentsBySubjectAndAccount(((Account)accountList.getSelectedItem()).getId(), ((Subject)subjectList.getSelectedItem()).getId(), jDateChooser2.getDate(),jDateChooser3.getDate());
         
        if((((Account)accountList.getSelectedItem()).getId() == 0) && (((Subject)subjectList.getSelectedItem()).getId() == 0) && !(jCheckBox1.isSelected()))
            toTable = paymentManager.findAllPayments();
        
        if((((Account)accountList.getSelectedItem()).getId() == 0) && (((Subject)subjectList.getSelectedItem()).getId() != 0) && !(jCheckBox1.isSelected()))
            toTable = expenseManager.getAllPaymentsBySubject(((Subject)subjectList.getSelectedItem()).getId());
        
        if((((Account)accountList.getSelectedItem()).getId() != 0) && (((Subject)subjectList.getSelectedItem()).getId() == 0) && !(jCheckBox1.isSelected()) )
            toTable = expenseManager.getAllPaymentsByAccount(((Account)accountList.getSelectedItem()).getId());
        
        if((((Account)accountList.getSelectedItem()).getId() != 0) && (((Subject)subjectList.getSelectedItem()).getId() != 0) && !(jCheckBox1.isSelected()) ){
            toTable = expenseManager.getAllPaymentsBySubjectAndAccount(((Account)accountList.getSelectedItem()).getId(), ((Subject)subjectList.getSelectedItem()).getId());
        }
        
        ((JPaymentTableModel)paymentTableModel.getModel()).refresh(toTable); 
    }
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String desc = jTextField2.getText();
        BigDecimal amount = null;
        try{
           amount = new BigDecimal(jTextField1.getText().replaceAll(",","."));
        }
        catch(NumberFormatException ex){
            //jDialog4.setVisible(true);   TODO: ErrorFrame
        }
        
        if (desc.equals("") || (amount == null)){
            //jDialog4.setVisible(true);  
        } else {
            
        Payment payment = new Payment();
        payment.setAccountId(((Account)jComboBox1.getSelectedItem()).getId());
        payment.setSubjectId(((Subject)jComboBox2.getSelectedItem()).getId());
        payment.setCategoryId(((Category)jComboBox3.getSelectedItem()).getId());
        payment.setDescription(desc);
        payment.setAmount(amount);
        payment.setDate(jDateChooser1.getDate());
        paymentManager.createPayment(payment);
       // new MainApplication.PaymentSwingWorker(MainApplication.PaymentActions.ADD_PAYMENT, payment).execute();
        }
        update();
        jFrame1.dispose();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accountList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JTable paymentTableModel;
    private javax.swing.JComboBox subjectList;
    // End of variables declaration//GEN-END:variables
}
